sudo: required
language: php
dist: trusty

php:
  - 7.1

services:
  - postgresql

addons:
  chrome: stable

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve > /dev/null 2>&1 &
  - php artisan dusk
  - ./vendor/bin/phpunit --coverage-clover clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -cF php
