dist: trusty
sudo: required
language: php

php:
  - 7.1

services:
  - postgresql

addons:
  apt:
    packages:
      - google-chrome-stable
      - chromium-chromedriver

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - echo "Installing ChromeDriver"
  - LATEST_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE) && wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$LATEST_VERSION/chromedriver_linux64.zip && sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/;
  - sudo ln -s /usr/local/bin/chromedriver ~/bin/chromedriver # add to path
  - sudo ln -sf /usr/local/bin/chromedriver ./vendor/laravel/dusk/bin/chromedriver-linux # add to dusk
  - psql -c 'create database bomberos_testing;' -U postgres
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate

script:
  - whereis chromium-chromedriver
  - whereis chromedriver
  - chromedriver --version
  - ls ./vendor/laravel/dusk/bin/
  - ./vendor/laravel/dusk/bin/chromedriver-linux --version
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve > /dev/null 2>&1 &
  - php artisan dusk
  - ./vendor/bin/phpunit --coverage-clover clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -cF php
