<?php
return ['jerarquia' => [1 => 'Oficial Superior',
                    2 => 'Oficial Jefe',
                    3 => 'Oficial Subalterno',
                    4 => 'Suboficial Superior',
                    5 => 'Suboficial Subalterno',
                    6 => 'Bombero',
                    7 => 'Cadete',
                    8 => 'Aspirante'],

'tipoAsistencia'=> [1 => '01 - Guardia - Comando - Tecnico - Ceremonial - Asistencia programada',
                    2 => '02 - En primera dotacion',
                    3 => '03 - En otra dotacion',
                    4 => '04 - En el cuartel',
                    5 => '05 - En comision',
                    6 => '06 - Licencia',
                    7 => '07 - Enfermo',
                    8 => '08 - Cumpliendo castigo',
                    9 => '09 - Con aviso',
                    10 => '10 - Sin aviso'],

'tipoServicio' => [ 1 => 'Incendio',
                    2 => 'Auxilio',
                    3 => 'Especiales',
                    4 => 'Desastre',
                    5 => 'Colaboracion',
                    6 => 'Guardia',
                    7 => 'Comando',
                    8 => 'Tecnico',
                    9 => 'Ceremonial',
                    10 => 'Productos quimicos',
                    11 => 'Forestales'],

'tipoAlarma' => [   null =>'Ninguna',
                    1 => 'Interna',
                    2 => 'Selectiva',
                    3 => 'General'],

'rubro' => [        1 => 'INCENDIO',
                    2 => 'RESCATE EN ALTURA',
                    3 => 'RESCATE EN ACCIDENTES',
                    4 => 'RESCATE-MATERIAL PESADO',
                    5 => 'RESCATE ACUÁTICO',
                    6 => 'SALVAMENTO Y SOCORRISMO',
                    7 => 'COMUNICACIONES',
                    8 => 'MATERIALES PELIGROSOS',
                    9 => 'ELEMENTOS DE COMPAÑIA',
                    10 => 'LOGISTICA - TRANSPORTE',
                    11 => 'EQUIPOS DE PROTECCIÓN PERSONAL',
                    12 => 'VARIOS'],

'estadovehiculo' => [1 => 'En servicio',
                    2 => 'Fuera de servicio',
                    3 => 'Baja'],

'meses' => [        1 => 'ENERO',
                    2 => 'FEBRERO',
                    3 => 'MARZO',
                    4 => 'ABRIL',
                    5 => 'MAYO',
                    6 => 'JUNIO',
                    7 => 'JULIO',
                    8 => 'AGOSTO',
                    9 => 'SEPTIEMBRE',
                    10 => 'OCTUBRE',
                    11 => 'NOVIEMBRE',
                    12 => 'DICIEMBRE'],


      ];
